/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsNoteInfo {
  path: string
  name: string
  modified?: string
  created?: string
  sizeBytes: number
}
export interface JsLink {
  target: string
  alias?: string
  heading?: string
  blockId?: string
  embed: boolean
  line: number
}
export interface JsTag {
  name: string
  line: number
}
export interface JsHeading {
  text: string
  level: number
  line: number
  slug: string
}
export interface JsBlockId {
  id: string
  line: number
  blockType: string
}
export interface JsTaskLink {
  to: string
  alias?: string
}
export interface JsTask {
  file: string
  line: number
  raw: string
  symbol: string
  description: string
  indent: number
  scheduled?: string
  due?: string
  done?: string
  start?: string
  created?: string
  cancelled?: string
  recurrence?: string
  onCompletion?: string
  id?: string
  dependsOn: Array<string>
  priority?: string
  links: Array<JsTaskLink>
  tags: Array<string>
  blockId?: string
}
export interface JsVaultielMetadata {
  id: string
  created: string
}
export interface JsLinkRef {
  from: string
  line: number
  context: string
  alias?: string
  heading?: string
  blockId?: string
  embed: boolean
}
/** Parse links from markdown content. */
export declare function parseLinks(content: string): Array<JsLink>
/** Parse tags from markdown content. */
export declare function parseContentTags(content: string): Array<JsTag>
/** Parse headings from markdown content. */
export declare function parseContentHeadings(content: string): Array<JsHeading>
/** Parse block IDs from markdown content. */
export declare function parseContentBlockIds(content: string): Array<JsBlockId>
export declare class JsVault {
  /** Open a vault at the specified path. */
  constructor(path: string)
  /** Get the vault root path. */
  get root(): string
  /** List all notes in the vault. */
  listNotes(): Array<string>
  /** List notes matching a glob pattern. */
  listNotesMatching(pattern: string): Array<string>
  /** Check if a note exists. */
  noteExists(path: string): boolean
  /** Get note content. */
  getContent(path: string): string
  /** Get note body (content without frontmatter). */
  getBody(path: string): string
  /** Get note frontmatter as JSON. */
  getFrontmatter(path: string): string | null
  /** Create a new note. */
  createNote(path: string, content: string): void
  /** Delete a note. */
  deleteNote(path: string): void
  /** Rename a note (without link propagation). */
  renameNote(from: string, to: string): void
  /** Resolve a note name or alias to a path. */
  resolveNote(query: string): string
  /** Parse links from a note. */
  getLinks(path: string): Array<JsLink>
  /** Parse tags from a note. */
  getTags(path: string): Array<JsTag>
  /** Parse headings from a note. */
  getHeadings(path: string): Array<JsHeading>
  /** Parse block IDs from a note. */
  getBlockIds(path: string): Array<JsBlockId>
  /** Parse tasks from a note, optionally filtering to tasks linking to a specific note. */
  getTasks(path: string, linksTo?: string | undefined | null): Array<JsTask>
  /** Set the content of a note (replaces body, preserves frontmatter). */
  setContent(path: string, content: string): void
  /** Modify a frontmatter field. */
  modifyFrontmatter(path: string, key: string, value: string): void
  /** Append content to a note. */
  appendContent(path: string, content: string): void
  /** Replace first occurrence of pattern in note content. */
  replaceContent(path: string, pattern: string, replacement: string): void
  /** Inspect a note — returns full JSON representation. */
  inspect(path: string): string
  /** Get incoming links to a note. */
  getIncomingLinks(path: string): Array<JsLinkRef>
  /** Get outgoing links from a note. */
  getOutgoingLinks(path: string): Array<JsLinkRef>
  /** Initialize vaultiel metadata for a note. */
  initMetadata(path: string, force: boolean): JsVaultielMetadata | null
  /** Get vaultiel metadata from a note. */
  getVaultielMetadata(path: string): JsVaultielMetadata | null
  /** Find a note by its vaultiel ID. */
  findById(id: string): string | null
}
